- name: Importar dashboard no Grafana via API
  hosts: localhost
  tasks:
    - name: Importar dashboard Node Exporter
      uri:
        url: http://localhost:3000/api/dashboards/db
        method: POST
        user: admin
        password: admin
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body: "{{ lookup('file', 'grafana/dashboard-node-exporter.json') }}"
        body_format: json
